# Tipo do carregador de mods - para NeoForge deve ser javafml
modLoader="javafml"

# Intervalo de versão do carregador
loaderVersion="[1,)"

# Licença do seu mod
license="MIT"

# Declaração do bloco do mod
[[mods]]
modId="undertale"
version="1.0.0"
displayName="undertale"

# Quem criou o mod
authors="Gabriel"

# A descrição do seu mod
description='''
Um mod que pacifica monstros e criaturas do Minecraft quando recebem uma Tag com o nome de 'Amigao'.
Feito para a versão 1.21.1 usando NeoForge!
'''

# Dependência Obrigatória: NeoForge
[[dependencies.undertale]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

# Dependência Obrigatória: Minecraft Base
[[dependencies.undertale]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"