# Tipo do carregador de mods - para NeoForge deve ser javafml
modLoader="javafml"

# Intervalo de versão do carregador
loaderVersion="[1,)"

# Licença do seu mod
license="MIT"

# Declaração do bloco do mod
[[mods]]
modId="undertale"
version="1.0.0"
displayName="Undertale"

# Quem criou o mod
authors="Gabriel"

# A descrição do seu mod
description='''
This mod adds things of Undertale (Sans armor set, the Real Knife, Sans bone entity).
Feito para a versão 1.21.1 usando NeoForge!
'''

# Dependência Obrigatória: NeoForge
[[dependencies.undertale]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

# Dependência Obrigatória: Minecraft Base
[[dependencies.undertale]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

# Dependência Obrigatória: Re-Avaritia (receitas usam avaritia:infinity_*)
[[dependencies.undertale]]
modId="avaritia"
type="required"
versionRange="[1.3.9,)"
ordering="NONE"
side="BOTH"

# Dependência Obrigatória: GeckoLib (animações da entidade do osso do Sans)
[[dependencies.undertale]]
modId="geckolib"
type="required"
versionRange="[4.6,)"
ordering="AFTER"
side="BOTH"
